### PR TITLE
Cross-tab copy / paste

### PR DESCRIPTION
**Pull request by joshlory**
copy

### CODE REVIEW

**Comment by Hamms** [comment]
I thought we had reasons for not wanting to do this; preventing students from pasting blocks into levels that don't have those blocks in the toolbox, etc

**Comment by balderdash** [comment]
Josh added better handling for unknown block types, so pasting unsupported blocks will just give you an ugly gray "unknown block" block rather than completely breaking blockly.

The curriculum question is another matter. We could make it a level option to enable/disable pasting, but I'm not sure if it would be even more annoying to have copy and paste that only works *sometimes*.

**Comment by Hamms** [comment]
@ryansloan @kiki-lee can you remind me of the potential issues with allowing this kind of copy-pasting?

**Comment by kiki-lee** [comment]
I think the biggest concern was cheating, but also I've been told that this is just really hard to do.

**Comment by kiki-lee** [comment]
I suppose someone could copy blocks from one skin to another (where they're not supported) and throw themselves into an error...but we'll need to figure that out before we move to a backpack, anyhow :)

**Comment by ryansloan** [comment]
I think that it's ok to ship this as-is, given that most of our K-5 students haven't quite figured out all this keyboard copy/paste business, and _most_ of the time having this ability wouldn't be a big issue anyway. We should address the cheating issue as part of the backpack work that we do in a few months..

**Comment by kiki-lee** [comment]
Quick FYI that I don't worry at all about the cheating aspect.  I think the amount that it requires students to think about other ways of solving the problem far outweighs the risk of them not having to manually enter expected code.

**Pull request merged**
