### PR TITLE
Use a curve that's actually 50px tall to check for bbox bug

### PR DESCRIPTION
**Pull request by balderdash**
Followup to https://github.com/code-dot-org/blockly/pull/7

Chrome has since fixed https://bugs.chromium.org/p/chromium/issues/detail?id=230599, but our bug-detector is giving us false positives. The current test path actually does extend into negative-y terroritory, so chrome correctly reports it as having a height greater than 50: 
image
The triangle has a height and width of 50, the little notch at the top left is the bezier curve you get by going from (0,0) to (0,0) with both control points at (0, -5)

I'm replacing it with a curve that extends from (0, 50) to (125, 0), with the first control point at (75, -25). This catches older versions of chrome that include the control point, and thus report the height as 75px, but not newer ones that correctly determine that the curve stays on the sunny side of the x-axis:
image

### CODE REVIEW

**Comment by balderdash** [comment]
This also fixes a bug in our block highlighting that's been bugging me for quite some time. Note the notches in the corners.
Before:
image

After:
image

**Comment by balderdash** [comment]
According to the chromium bug page, Chrome 62 and older. I spot-checked chrome 60 and saw that it was still present.

**Comment by Hamms** [comment]
Might be nice to add a note in there saying something to the effect of "if at any point we remove support for Chrome version 62 and older, this bug detection can be removed"

**Comment by balderdash** [comment]
Turns out this also fixed another bug that has been annoying me:
Before:
image

After:
image

**Pull request merged**
